name: Evaluacion Practica Ciao-Prolog

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del alumno
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ejecutar bateria de pruebas en Ciao-Prolog
        run: |
          docker run --rm \
          -v "$GITHUB_WORKSPACE:/code" \
          -w /code \
          ciaolang/ciao:latest \
          sh -c "/root/.ciao/bin/ciao main -f evaluador.pl > resultado.txt 2>&1 || /root/.ciaoroot/master/bin/ciao main -f evaluador.pl > resultado.txt 2>&1 || true"

	  cat resultado.txt

      - name: Publicar feedback en el Step Summary
        run: |
          echo "## Resultado de la Evaluacion" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat resultado.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY